### ISSUE TITLE
Anytime I update an npm package globally, i get a peerDependency error releated to byots

### ISSUE THREAD

**Issue by JuanAntelo** [basarat/byots#1]
It's been a few days and I am still unable to find the root cause. Starting to suspect byots could be the issue. Here is the message: 

```
npm ERR! peerinvalid The package typescript@2.1.0-dev.20160724 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer byots@2.1.0-dev.20160724.9.14 wants typescript@*
```

Could this be releated to byots?

**Comment by basarat** [comment]
That version is suspiciously same as : https://github.com/basarat/byots/blob/76dfc5af46d608b68f690f0b76fec2aa120b508b/package.json#L27 
- Which version of NPM / Node? 

fwiw I use it in alm and its working fine : https://github.com/alm-tools/alm/blob/5d19e5be2f34687d732b2b2b9256f9a4edc3860d/package.json#L72 / https://github.com/alm-tools/alm/blob/5d19e5be2f34687d732b2b2b9256f9a4edc3860d/package.json#L46

**Comment by JuanAntelo** [comment]
v4.1.1

**Comment by guncha** [comment]
Seeing the same issue on Travis-CI:

```
$ node --version
v4.1.2
$ npm --version
2.14.4
$ nvm --version
0.32.0
```

https://travis-ci.org/TypeStrong/atom-typescript/builds/169931303

**Comment by basarat** [comment]
Suspect npm v2 issue. Try the build with node v5 (comes with npm v3). 

More : Key reason is the `@next` tag doesn't match `*` for npm v2. Suspect it does for v3 which is why I haven't experienced it for quite a while

**Comment by JuanAntelo** [comment]
Thanks for the recommendation, when I upgraded my npm I stopped experiencing this issue
