### ISSUE TITLE
[Question] tsc or byots ? how use it ?

### ISSUE THREAD

**Issue by c0ncentus** [basarat/byots#10]
Hi, 

tsc is awesome tool for build my npm package because I generate with "tsc ." .js files and .d.ts with it.

Is the package useful to generate .js from  .js files and .d.ts files ?

if yes, how ?

from an other issue "Problem is, I don't get how i'm supposed to use it since there is very little documentation...
Some explenations would be very helpful." from https://github.com/basarat/byots/issues/5
I don't really know how to use it.

Also I read https://basarat.gitbook.io/typescript/overview#byots but still no idea for use it : /.

**Comment by basarat** [comment]
`tsc` has nothing to do with `byots`. BYOTS is for people that want to work with TypeScript programatically.
