### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by guncha** [basarat/byots#2]
Seems like the automatic build process has fallen behind.

Do you think it would be possible to do the typescript.d.ts generation in a `postinstall` step for this package, allowing to always use the most recent local version of Typescript?

**Comment by basarat** [comment]
> Do you think it would be possible to do the typescript.d.ts generation in a postinstall step for this package,

No. Because it needs the _source_ code for typescript, so you would really need the close that project.

> Seems like the automatic build process has fallen behind.

Let me check :rose:

**Comment by basarat** [comment]
> Seems like the automatic build process has fallen behind.

The build is running everynight (last build 19 hours ago https://travis-ci.org/basarat/byots) and still pushing to github (last release 19 hours ago https://github.com/basarat/byots/releases) however no edits are present and hence no new commits. At least a edit to package.json should have been made. Checking what is going wrong :rose:

**Comment by basarat** [comment]
Running locally worked fine :-/ 

![image](https://cloud.githubusercontent.com/assets/874898/19623313/a7f4d9d4-9910-11e6-94e8-eaad41668fac.png)

On the build log I see `detached head` : https://travis-ci.org/basarat/byots/builds/169683870#L892

Hopefully explicit checkout master will fix that. Seems like a travis problem :-/ A past version of me seems to have done this before e.g. https://github.com/basarat/monaco/blob/ae0cf2b931ab4a2957803d94f94d4fef92bd3579/release.sh#L24 :rose: :)

**Comment by basarat** [comment]
This should fix it : https://github.com/basarat/byots/commit/c3939462433c21e7ac267d2de186561e92ddf782 I'll still monitor it over the next week. For now its good to go :heart: 👍

**Comment by guncha** [comment]
Thank you 👍
