### ISSUE TITLE
What should I use to build a ts npm package for node ?

### ISSUE THREAD

**Issue by etienne-dldc** [basarat/byots#5]
Hi ✋ 

I want to write a package for nodeJS in typescript, I already knew `tsc` but it's deprecated now and point to `ntypescript `. But apparently `ntypescript` is Dead and `byots` is the new thing...

Problem is, I don't get how i'm supposed to use it since there is very little documentation...
Some explenations would be very helpful.

Thanks, Etienne.

**Comment by basarat** [comment]
> I want to write a package for nodeJS in typescript,

You only need TypeScript! 

# More 
Checkout the node quickstart : https://basarat.gitbooks.io/typescript/content/docs/quick/nodejs.html :rose:
