### ISSUE TITLE
Error: BindingElementGrandparent - Property 'parent' does not exist

### ISSUE THREAD

**Issue by bendtherules** [basarat/byots#6]
I am getting this error with newer version of byots (2.9.0-dev.20180411.1.10) -

```
node_modules/byots/bin/typescript.d.ts:627:63 - error TS2339: Property 'parent' does not exist on type 'ObjectBindingPattern | ArrayBindingPattern | undefined'.

627     type BindingElementGrandparent = BindingElement["parent"]["parent"];
```
The problem is (as you can understand ) that `BindingElement["parent"]` can be undefined and hence the next parent accessor might be illegal.

Just removing this line manually solves the problem for me.

I am not sure how this project automatically creates the nightly builds, but can we just remove it somehow so that it doesn't break anyone's build who is using this project? I understand that it is unmaintained, but some help on fixing this will be very much appreciated.

Edit: I initially thought that this is something that doesn't exist in typescript source, but somehow added in "byots", but I was wrong. It also exists there. https://github.com/Microsoft/TypeScript/blame/84b12910e80a332473eb7f54a04a858c134ebb6b/src/compiler/types.ts#L870

But when using Typescript instead of byots, it doesn't raise this error. Is it so because internal (commented) typedefs which cause errors are ignored by the compiler? Should I raise this as a Typescript bug instead?

**Comment by basarat** [comment]
Use the null assertion : `BindingElement["parent"]!["parent"]`. https://basarat.gitbooks.io/typescript/docs/options/strictNullChecks.html

**Comment by bendtherules** [comment]
Thanks for the solution. But using byots as dependency will still have the problem, as it will get replaced with the broken code on every new nom install.
