### ISSUE TITLE
Conflict with stable build

### ISSUE THREAD

**Issue by nonara** [basarat/byots#8]
Hi. I'm using the library `ts-query` within a transformer. I import from `byots` in the transformer, as I need access to the internals. However, when I pass off `SourceFile` to `ts-query`, it fails saying that `kind` is different.

`ts-query` imports from the same typescript installation, however, it doesn't use byots. It occurred to me that differences in the enums (flags, kind, etc) could cause a major problem.

I'm using `typescript` 3.8.3 (stable release) and `byots` is `3.8.0-dev.20200201.4.49`. I would prefer not to install a typescript dev branch. Would it be possible to release for stable builds of typescript as well? 

**Edit:** 
It's possible that there are simply differences in `SyntaxKind` due to internals not being exposed. I don't mind using an `<any>` for tsquery arguments, which is what I was doing before. 

The real question is whether or not the last 3.8.0-dev byots release is guaranteed to line up with the stable release (minus the internals). Is it possible that they will not sync up?

**Comment by basarat** [comment]
> The real question is whether or not the last 3.8.0-dev byots release is guaranteed to line up with the stable release (minus the internals). Is it possible that they will not sync up


Indeed it does. 

Commits in 3.8:  https://github.com/microsoft/TypeScript/commits/release-3.8
Commits in master for same duration : https://github.com/microsoft/TypeScript/commits/master?after=96f01227d4f300ad85e5e470595b5c7bd96d9304+174

There is cherry picking going on making the release different from the master. 


> It occurred to me that differences in the enums (flags, kind, etc) could cause a major problem.

Unlikely as the enums, flags, kind are append only so numbers for the common members should be the same. I haven't run into any issues currently using TS 3.8.2 with BYOTS 3.9.0-dev in [designtsx](https://designtsx.com/).

I would recommend keeping them consistent though i.e. use byots + typescript@next (the master branch build from MS) :rose:

**Comment by nonara** [comment]
I have confirmed that enum values can differ between versions. 

Another potential issue would be if an internal type changes between minor versions. It is reasonable to assume that this is a possibility.

Overall, using a nightly build is not an option for anyone whose project requires a stable build an an assurance of an exact match in the types. Would you be amenable to updating the cron to publish for tagged versions as well? I believe it would be appreciated by all who would like to use byots with the stable build, which is likely the majority.

In the mean time, I've created a script to run through the process of building and extracting the types to a file, but I thought I'd drop a message here just in case.

Thanks for your work!

**Comment by basarat** [comment]
> I have confirmed that enum values can differ between versions.

Thanks! : https://github.com/basarat/byots/commit/fa8fdc6bd0bf08527b3b4a6595be7b8d22ebe72f 

> Overall, using a nightly build is not an option for anyone whose project requires a stable build an an assurance of an exact match in the types. Would you be amenable to updating the cron to publish for tagged versions as well? I believe it would be appreciated by all who would like to use byots with the stable build, which is likely the majority.

I don't update byots in my code often. I only do it when there is some really cool TS api that I need to play with and in that case I *need* the nightly build. 

I'll be happy to link to your work if you want :rose:

**Comment by nonara** [comment]
Sounds good! I've gone ahead and built it out to be a cron script, which I'll post to GH shortly. I'm augmenting the typescript module, as well, so it should allow simply adding the dev dependency and all types should be recognized with a direct import / require of 'typescript'.

I've replicated your pre and post fixes. 

One question though: is there a reason that you're using `typescriptServices.d.ts` instead of `typescript.d.ts`? I'd probably prefer the latter just to be sure that there's never any divergence in the future, but the old adage comes to mind...

> Never tear down a fence until you know the reason it was put up. - G. K. Chesterton

**Comment by basarat** [comment]
> you're using `typescriptServices.d.ts` instead of `typescript.d.ts`

`typescriptServices` is `typescript` plus the language service :rose:

**Comment by nonara** [comment]
Just wrapped it up! You can find it here: https://github.com/nonara/ts-expose-internals

## Differences

- Builds for new releases only
- Uses module augmentation (can import directly from `typescript`)

## Environment

- It's running as a systemd oneshot with a 12hr timer
- Has OnFailure alerts via email
- Running on my always-on primary VPS

**Comment by basarat** [comment]
Thanks. I've added https://github.com/basarat/byots#ts-expose-internals :rose:

**Comment by nonara** [comment]
Cheers 😄
