### ISSUE TITLE
Can I use `isTypeIdenticalTo` internal API?

### ISSUE THREAD

**Issue by SamVerschueren** [basarat/byots#9]
I'm looking into `byots` instead of rolling my own custom TS version in [tsd](https://github.com/SamVerschueren/tsd).

I noticed that I can't use `isTypeIdenticalTo`, unless I'm doing something wrong here 🤔. Actually, that's the only API I'm currently interested in.

**Comment by basarat** [comment]
I don't see `isTypeIdenticalTo` in Microsoft/TypeScript : https://github.com/microsoft/TypeScript/search?q=isTypeIdenticalTo&unscoped_q=isTypeIdenticalTo

![image](https://user-images.githubusercontent.com/874898/86772732-ed2d8700-c097-11ea-9d33-28a652ca4f6c.png)

Maybe its been removed. 

Still let me know if there is something in Microsoft/TypeScript that's not coming in byots and I'll have a look  :rose:
